### ISSUE TITLE
cannot import name 'corner_pool_ext' from 'mmdet.ops.corner_pool'

### ISSUE THREAD

**Issue by Huiimin5** [longrongyang/LNCIS#3]
Hello when I was trying to train your model I got this error. I checked ./mmdet/ops/corner_pool/ and I did not see corner_pool_ext. 
![image](https://user-images.githubusercontent.com/11154631/106346248-936d0280-62f0-11eb-9ea4-c62cab7d8290.png)
But in the same directory of mmdetection I can see:
![image](https://user-images.githubusercontent.com/11154631/106346261-bb5c6600-62f0-11eb-9f85-d28557e09864.png)

I am wondering how you got this work in your environment? 

Thank you so much for your help.

**Comment by longrongyang** [comment]
Sorry for that. I need cost some time to check this bug.

Our code strictly follows mmdetection. The modification is only loss functions and config files. Hence, you can firstly install a mmdetection. Then, based on mmdetection of any versions, the modification about losses and configs can be finished easily.

**Comment by longrongyang** [comment]
I have checked it ever. The difference comes from the difference of mmdetection versions. As I have mentioned, the project is based on mmdetection v2.2.0. Files that I give are the same with those in mmedtection v2.2.0. Some files can be obtained after compilation.
