### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [longrongyang/LNCIS#4]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by longrongyang** [comment]
Sorry to response so late.

First, we do not conduct any experiments on tabular data. Therefore, I have no idea that whether it can work on tabular data. However, it can be helpful to analyze the difference between vision data (i.e., images) and tabular data to know whether the method can be useful.

Second, the work aims to depress gradients provided by noisy samples. Theoretically, it can not be used to identify noisy instances. 

A simple way to identify noisy instances is to find out samples whose loss values are large in the mature stage of train. Futhermore, Sample Selection is a series of methods in noisy-label learning, such as co-teaching. These methods use the teacher-student model to select out noisy or clean samples. 

Wish to help you.

**Comment by nazaretl** [comment]
thank you, this helps!
